"use strict";
Object.defineProperty(exports, Symbol.toStringTag, { value: "Module" });
const isString = (value) => typeof value === "string";
const isNumber = (value) => typeof value === "number";
const isBoolean = (value) => typeof value === "boolean";
const isArray = (value) => Array.isArray(value);
const isObject = (value) => typeof value === "object" && !Array.isArray(value);
const isFunction = (value) => typeof value === "function";
const isPromise = (value) => value instanceof Promise;
const isWindow = (value) => value === window;
exports.isArray = isArray;
exports.isBoolean = isBoolean;
exports.isFunction = isFunction;
exports.isNumber = isNumber;
exports.isObject = isObject;
exports.isPromise = isPromise;
exports.isString = isString;
exports.isWindow = isWindow;
